### ISSUE TITLE
Easy fixes

### ISSUE THREAD

**Issue by Teque5** [mafik/ansi-art#2]
Neat package; better output than most ANSI renderers I've seen.

Few thoughts:

1. You probably want to remove that 1MB `ogg` file from the repo that serves no purpose
2. I'd be useful to have an example that didn't read from a pre-baked `example-image.h` and `example-font.h`. I think most people just want `maf --font <optional font> image.png` and get output. Next level would be a simple makefile that just has `make` and `make install` to `.local/bin` or whatever.
3. On ubuntu 20.04 I needed this line to run your example:
```bash
g++ -pthread -std=c++2a -I. example.cc maf/*.cc `pkg-config --cflags --libs freetype2` -o example
```
4. maybe toss all those example images in a `docs\` folder?
5. the repo could be quite a bit smaller if you convert those pngs to webp `cwebp -q 80 sample1.png -o sample1.webp`

:D

**Comment by mafik** [comment]
Thanks :) I've cleaned up the repo a bit.

I'd rather keep this as a C++ library and focus on making it easy to package / embed. CLI comes with a whole new set of challenges. I'm sure somebody else would do this better than me :P
