### ISSUE TITLE
Question about sample1.png, sample2.png, etc

### ISSUE THREAD

**Issue by adsr** [mafik/ansi-art#3]
Nice. I'm curious what font, emulator, width, etc were used to produce sample1.png? It looks crisper than example-result.png, which is what the result looks like on my setup.

**Comment by mafik** [comment]
Right - the most important trick is to find a good font. The best ones have a lot of box-shapes (triangles, checkerboards, trapezoids). The one I used for sample1 is "Iosevka Fixed". Another nice one is "Julia Mono" (the one used on the interactive demo page). 

Generally speaking you can roughly guess when a font will produce good graphics by looking at its size. Anything above 1MB has a good change of having decent set of glyphs.
